version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.27.0
    restart: always
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: './weaviate-data'
      DEFAULT_VECTORIZER_MODULE: 'none'   # we'll provide our own vectors
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - ./weaviate-data:/var/lib/weaviate
